# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PHYMOBATe_tab_2_0.ui'
#
# Created: Mon Sep 12 15:42:51 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PHYMOBAT(object):
    def setupUi(self, PHYMOBAT):
        PHYMOBAT.setObjectName(_fromUtf8("PHYMOBAT"))
        PHYMOBAT.resize(550, 607)
        self.centralwidget = QtGui.QWidget(PHYMOBAT)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_multiprocess = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_multiprocess.setCheckable(True)
        self.checkBox_multiprocess.setChecked(True)
        self.checkBox_multiprocess.setAutoRepeat(False)
        self.checkBox_multiprocess.setObjectName(_fromUtf8("checkBox_multiprocess"))
        self.gridLayout.addWidget(self.checkBox_multiprocess, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_browser_area_path = QtGui.QPushButton(self.tab)
        self.pushButton_browser_area_path.setObjectName(_fromUtf8("pushButton_browser_area_path"))
        self.gridLayout_3.addWidget(self.pushButton_browser_area_path, 5, 5, 1, 1)
        self.pushButton_browser_principal_folder = QtGui.QPushButton(self.tab)
        self.pushButton_browser_principal_folder.setObjectName(_fromUtf8("pushButton_browser_principal_folder"))
        self.gridLayout_3.addWidget(self.pushButton_browser_principal_folder, 1, 5, 1, 1)
        self.label_principal_folder = QtGui.QLabel(self.tab)
        self.label_principal_folder.setObjectName(_fromUtf8("label_principal_folder"))
        self.gridLayout_3.addWidget(self.label_principal_folder, 0, 0, 1, 2)
        self.label_area_path = QtGui.QLabel(self.tab)
        self.label_area_path.setObjectName(_fromUtf8("label_area_path"))
        self.gridLayout_3.addWidget(self.label_area_path, 4, 0, 1, 2)
        self.checkBox_download = QtGui.QCheckBox(self.tab)
        self.checkBox_download.setObjectName(_fromUtf8("checkBox_download"))
        self.gridLayout_3.addWidget(self.checkBox_download, 7, 0, 1, 2)
        self.lineEdit_password = QtGui.QLineEdit(self.tab)
        self.lineEdit_password.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_password.setObjectName(_fromUtf8("lineEdit_password"))
        self.gridLayout_3.addWidget(self.lineEdit_password, 9, 4, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 3, 2, 1, 1)
        self.pushButton_browser_VHRS = QtGui.QPushButton(self.tab)
        self.pushButton_browser_VHRS.setObjectName(_fromUtf8("pushButton_browser_VHRS"))
        self.gridLayout_3.addWidget(self.pushButton_browser_VHRS, 14, 5, 1, 1)
        self.label_id_theia = QtGui.QLabel(self.tab)
        self.label_id_theia.setObjectName(_fromUtf8("label_id_theia"))
        self.gridLayout_3.addWidget(self.label_id_theia, 8, 0, 1, 2)
        self.label_password = QtGui.QLabel(self.tab)
        self.label_password.setObjectName(_fromUtf8("label_password"))
        self.gridLayout_3.addWidget(self.label_password, 9, 3, 1, 1)
        self.lineEdit_user = QtGui.QLineEdit(self.tab)
        self.lineEdit_user.setObjectName(_fromUtf8("lineEdit_user"))
        self.gridLayout_3.addWidget(self.lineEdit_user, 9, 1, 1, 1)
        self.label_user = QtGui.QLabel(self.tab)
        self.label_user.setObjectName(_fromUtf8("label_user"))
        self.gridLayout_3.addWidget(self.label_user, 9, 0, 1, 1)
        self.checkBox_VHRS = QtGui.QCheckBox(self.tab)
        self.checkBox_VHRS.setObjectName(_fromUtf8("checkBox_VHRS"))
        self.gridLayout_3.addWidget(self.checkBox_VHRS, 13, 0, 1, 2)
        self.label_year_images = QtGui.QLabel(self.tab)
        self.label_year_images.setObjectName(_fromUtf8("label_year_images"))
        self.gridLayout_3.addWidget(self.label_year_images, 3, 0, 1, 2)
        self.lineEdit_VHRS = QtGui.QLineEdit(self.tab)
        self.lineEdit_VHRS.setObjectName(_fromUtf8("lineEdit_VHRS"))
        self.gridLayout_3.addWidget(self.lineEdit_VHRS, 14, 0, 1, 5)
        self.lineEdit_year_images = QtGui.QLineEdit(self.tab)
        self.lineEdit_year_images.setObjectName(_fromUtf8("lineEdit_year_images"))
        self.gridLayout_3.addWidget(self.lineEdit_year_images, 3, 3, 1, 1)
        self.checkBox_listing = QtGui.QCheckBox(self.tab)
        self.checkBox_listing.setObjectName(_fromUtf8("checkBox_listing"))
        self.gridLayout_3.addWidget(self.checkBox_listing, 6, 0, 1, 2)
        self.comboBox_captor = QtGui.QComboBox(self.tab)
        self.comboBox_captor.setObjectName(_fromUtf8("comboBox_captor"))
        self.comboBox_captor.addItem(_fromUtf8(""))
        self.comboBox_captor.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_captor, 2, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 9, 2, 1, 1)
        self.lineEdit_area_path = QtGui.QLineEdit(self.tab)
        self.lineEdit_area_path.setObjectName(_fromUtf8("lineEdit_area_path"))
        self.gridLayout_3.addWidget(self.lineEdit_area_path, 5, 0, 1, 5)
        self.label_captor = QtGui.QLabel(self.tab)
        self.label_captor.setObjectName(_fromUtf8("label_captor"))
        self.gridLayout_3.addWidget(self.label_captor, 2, 0, 1, 3)
        self.lineEdit_principal_folder = QtGui.QLineEdit(self.tab)
        self.lineEdit_principal_folder.setObjectName(_fromUtf8("lineEdit_principal_folder"))
        self.gridLayout_3.addWidget(self.lineEdit_principal_folder, 1, 0, 1, 5)
        self.checkBox_MNT = QtGui.QCheckBox(self.tab)
        self.checkBox_MNT.setObjectName(_fromUtf8("checkBox_MNT"))
        self.gridLayout_3.addWidget(self.checkBox_MNT, 11, 0, 1, 1)
        self.label_listing = QtGui.QLabel(self.tab)
        self.label_listing.setObjectName(_fromUtf8("label_listing"))
        self.gridLayout_3.addWidget(self.label_listing, 6, 3, 1, 1)
        self.pushButton_browser_MNT = QtGui.QPushButton(self.tab)
        self.pushButton_browser_MNT.setObjectName(_fromUtf8("pushButton_browser_MNT"))
        self.gridLayout_3.addWidget(self.pushButton_browser_MNT, 12, 5, 1, 1)
        self.lineEdit_MNT = QtGui.QLineEdit(self.tab)
        self.lineEdit_MNT.setObjectName(_fromUtf8("lineEdit_MNT"))
        self.gridLayout_3.addWidget(self.lineEdit_MNT, 12, 0, 1, 5)
        self.checkBox_processing = QtGui.QCheckBox(self.tab)
        self.checkBox_processing.setObjectName(_fromUtf8("checkBox_processing"))
        self.gridLayout_3.addWidget(self.checkBox_processing, 10, 0, 1, 4)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButton_img_sample = QtGui.QPushButton(self.tab_2)
        self.pushButton_img_sample.setObjectName(_fromUtf8("pushButton_img_sample"))
        self.gridLayout_4.addWidget(self.pushButton_img_sample, 8, 4, 1, 1)
        self.checkBox_RPG = QtGui.QCheckBox(self.tab_2)
        self.checkBox_RPG.setObjectName(_fromUtf8("checkBox_RPG"))
        self.gridLayout_4.addWidget(self.checkBox_RPG, 9, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(49, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 10, 1, 1, 1)
        self.pushButton_clear_sample = QtGui.QPushButton(self.tab_2)
        self.pushButton_clear_sample.setObjectName(_fromUtf8("pushButton_clear_sample"))
        self.gridLayout_4.addWidget(self.pushButton_clear_sample, 10, 2, 1, 2)
        self.checkBox_img_sample = QtGui.QCheckBox(self.tab_2)
        self.checkBox_img_sample.setObjectName(_fromUtf8("checkBox_img_sample"))
        self.gridLayout_4.addWidget(self.checkBox_img_sample, 7, 0, 1, 5)
        self.lineEdit_select_sample_fieldname_1 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_select_sample_fieldname_1.setObjectName(_fromUtf8("lineEdit_select_sample_fieldname_1"))
        self.gridLayout_4.addWidget(self.lineEdit_select_sample_fieldname_1, 4, 3, 1, 1)
        self.lineEdit_select_sample_fieldname_2 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_select_sample_fieldname_2.setObjectName(_fromUtf8("lineEdit_select_sample_fieldname_2"))
        self.gridLayout_4.addWidget(self.lineEdit_select_sample_fieldname_2, 4, 4, 1, 1)
        self.lineEdit_img_sample = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_img_sample.setObjectName(_fromUtf8("lineEdit_img_sample"))
        self.gridLayout_4.addWidget(self.lineEdit_img_sample, 8, 0, 1, 4)
        spacerItem3 = QtGui.QSpacerItem(49, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 5, 1, 1, 1)
        self.lineEdit_select_sample_class_2 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_select_sample_class_2.setObjectName(_fromUtf8("lineEdit_select_sample_class_2"))
        self.gridLayout_4.addWidget(self.lineEdit_select_sample_class_2, 5, 4, 1, 1)
        self.label_select_sample_fieldname = QtGui.QLabel(self.tab_2)
        self.label_select_sample_fieldname.setObjectName(_fromUtf8("label_select_sample_fieldname"))
        self.gridLayout_4.addWidget(self.label_select_sample_fieldname, 4, 0, 1, 1)
        self.pushButton_add_sample = QtGui.QPushButton(self.tab_2)
        self.pushButton_add_sample.setObjectName(_fromUtf8("pushButton_add_sample"))
        self.gridLayout_4.addWidget(self.pushButton_add_sample, 10, 4, 1, 1)
        self.plainTextEdit_sample = QtGui.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_sample.setObjectName(_fromUtf8("plainTextEdit_sample"))
        self.gridLayout_4.addWidget(self.plainTextEdit_sample, 11, 0, 1, 5)
        self.lineEdit_select_sample_nb_poly = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_select_sample_nb_poly.setObjectName(_fromUtf8("lineEdit_select_sample_nb_poly"))
        self.gridLayout_4.addWidget(self.lineEdit_select_sample_nb_poly, 6, 4, 1, 1)
        self.label_sample_path = QtGui.QLabel(self.tab_2)
        self.label_sample_path.setObjectName(_fromUtf8("label_sample_path"))
        self.gridLayout_4.addWidget(self.label_sample_path, 0, 0, 1, 1)
        self.label_select_sample_nb_poly = QtGui.QLabel(self.tab_2)
        self.label_select_sample_nb_poly.setObjectName(_fromUtf8("label_select_sample_nb_poly"))
        self.gridLayout_4.addWidget(self.label_select_sample_nb_poly, 6, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(49, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 4, 1, 1, 1)
        self.pushButton_browser_sample_path = QtGui.QPushButton(self.tab_2)
        self.pushButton_browser_sample_path.setObjectName(_fromUtf8("pushButton_browser_sample_path"))
        self.gridLayout_4.addWidget(self.pushButton_browser_sample_path, 1, 4, 1, 1)
        self.label_select_sample_class = QtGui.QLabel(self.tab_2)
        self.label_select_sample_class.setObjectName(_fromUtf8("label_select_sample_class"))
        self.gridLayout_4.addWidget(self.label_select_sample_class, 5, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(106, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 6, 2, 1, 2)
        self.label_select_sample_class_1 = QtGui.QLabel(self.tab_2)
        self.label_select_sample_class_1.setObjectName(_fromUtf8("label_select_sample_class_1"))
        self.gridLayout_4.addWidget(self.label_select_sample_class_1, 2, 2, 1, 2)
        self.lineEdit_sample_path = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_sample_path.setObjectName(_fromUtf8("lineEdit_sample_path"))
        self.gridLayout_4.addWidget(self.lineEdit_sample_path, 1, 0, 1, 4)
        self.label_select_sample = QtGui.QLabel(self.tab_2)
        self.label_select_sample.setObjectName(_fromUtf8("label_select_sample"))
        self.gridLayout_4.addWidget(self.label_select_sample, 2, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(49, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 6, 1, 1, 1)
        self.label_select_sample_class_2 = QtGui.QLabel(self.tab_2)
        self.label_select_sample_class_2.setObjectName(_fromUtf8("label_select_sample_class_2"))
        self.gridLayout_4.addWidget(self.label_select_sample_class_2, 2, 4, 1, 1)
        self.checkBox_threshold = QtGui.QCheckBox(self.tab_2)
        self.checkBox_threshold.setObjectName(_fromUtf8("checkBox_threshold"))
        self.gridLayout_4.addWidget(self.checkBox_threshold, 12, 0, 1, 3)
        self.lineEdit_select_sample_class_1 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_select_sample_class_1.setObjectName(_fromUtf8("lineEdit_select_sample_class_1"))
        self.gridLayout_4.addWidget(self.lineEdit_select_sample_class_1, 5, 3, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_area_fieldtype = QtGui.QLabel(self.tab_3)
        self.label_area_fieldtype.setObjectName(_fromUtf8("label_area_fieldtype"))
        self.gridLayout_2.addWidget(self.label_area_fieldtype, 8, 3, 1, 1)
        self.label_area_fieldname = QtGui.QLabel(self.tab_3)
        self.label_area_fieldname.setObjectName(_fromUtf8("label_area_fieldname"))
        self.gridLayout_2.addWidget(self.label_area_fieldname, 7, 3, 1, 1)
#         self.label_chps_type_2 = QtGui.QLabel(self.tab_3)
#         self.label_chps_type_2.setObjectName(_fromUtf8("label_chps_type_2"))
#         self.gridLayout_2.addWidget(self.label_chps_type_2, 14, 2, 1, 1)
        self.checkBox_classifier_2 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_classifier_2.setObjectName(_fromUtf8("checkBox_classifier_2"))
        self.gridLayout_2.addWidget(self.checkBox_classifier_2, 12, 0, 1, 5)
#         self.label_chps_type_3 = QtGui.QLabel(self.tab_3)
#         self.label_chps_type_3.setObjectName(_fromUtf8("label_chps_type_3"))
#         self.gridLayout_2.addWidget(self.label_chps_type_3, 17, 2, 1, 1)
#         self.lineEdit_fieldname_23 = QtGui.QLineEdit(self.tab_3)
#         self.lineEdit_fieldname_23.setObjectName(_fromUtf8("lineEdit_fieldname_23"))
#         self.gridLayout_2.addWidget(self.lineEdit_fieldname_23, 16, 4, 1, 1)
        self.label_ouput = QtGui.QLabel(self.tab_3)
        self.label_ouput.setObjectName(_fromUtf8("label_ouput"))
        self.gridLayout_2.addWidget(self.label_ouput, 4, 0, 1, 3)
#         self.lineEdit_fieldname_13 = QtGui.QLineEdit(self.tab_3)
#         self.lineEdit_fieldname_13.setObjectName(_fromUtf8("lineEdit_fieldname_13"))
#         self.gridLayout_2.addWidget(self.lineEdit_fieldname_13, 16, 3, 1, 1)
#         self.comboBox_fieldname_12 = QtGui.QComboBox(self.tab_3)
#         self.comboBox_fieldname_12.setObjectName(_fromUtf8("comboBox_fieldname_12"))
#         self.gridLayout_2.addWidget(self.comboBox_fieldname_12, 14, 3, 1, 1)
        self.label_chps_name_0 = QtGui.QLabel(self.tab_3)
        self.label_chps_name_0.setObjectName(_fromUtf8("label_chps_name_0"))
        self.gridLayout_2.addWidget(self.label_chps_name_0, 7, 0, 1, 1)
        self.label_segmentation = QtGui.QLabel(self.tab_3)
        self.label_segmentation.setObjectName(_fromUtf8("label_segmentation"))
        self.gridLayout_2.addWidget(self.label_segmentation, 0, 0, 1, 2)
#         self.comboBox_fieldname_3 = QtGui.QComboBox(self.tab_3)
#         self.comboBox_fieldname_3.setObjectName(_fromUtf8("comboBox_fieldname_3"))
#         self.gridLayout_2.addWidget(self.comboBox_fieldname_3, 17, 5, 1, 1)
        self.lineEdit_output = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_output.setObjectName(_fromUtf8("lineEdit_output"))
        self.gridLayout_2.addWidget(self.lineEdit_output, 5, 0, 1, 6)
#         self.lineEdit_fieldname_3 = QtGui.QLineEdit(self.tab_3)
#         self.lineEdit_fieldname_3.setObjectName(_fromUtf8("lineEdit_fieldname_3"))
#         self.gridLayout_2.addWidget(self.lineEdit_fieldname_3, 16, 5, 1, 1)
        self.label_id_fieldtype = QtGui.QLabel(self.tab_3)
        self.label_id_fieldtype.setObjectName(_fromUtf8("label_id_fieldtype"))
        self.gridLayout_2.addWidget(self.label_id_fieldtype, 8, 1, 1, 1)
        self.checkBox_classifier_3 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_classifier_3.setObjectName(_fromUtf8("checkBox_classifier_3"))
        self.gridLayout_2.addWidget(self.checkBox_classifier_3, 15, 0, 1, 5)
#         self.label_chps_name_2 = QtGui.QLabel(self.tab_3)
#         self.label_chps_name_2.setObjectName(_fromUtf8("label_chps_name_2"))
#         self.gridLayout_2.addWidget(self.label_chps_name_2, 13, 2, 1, 1)
#         self.comboBox_fieldname_23 = QtGui.QComboBox(self.tab_3)
#         self.comboBox_fieldname_23.setObjectName(_fromUtf8("comboBox_fieldname_23"))
#         self.gridLayout_2.addWidget(self.comboBox_fieldname_23, 17, 4, 1, 1)
#         self.lineEdit_fieldname_12 = QtGui.QLineEdit(self.tab_3)
#         self.lineEdit_fieldname_12.setObjectName(_fromUtf8("lineEdit_fieldname_12"))
#         self.gridLayout_2.addWidget(self.lineEdit_fieldname_12, 13, 3, 1, 1)
        self.radioButton_s = QtGui.QRadioButton(self.tab_3)
        self.radioButton_s.setObjectName(_fromUtf8("radioButton_s"))
        self.gridLayout_2.addWidget(self.radioButton_s, 3, 3, 1, 3)
        self.pushButton_browser_output = QtGui.QPushButton(self.tab_3)
        self.pushButton_browser_output.setObjectName(_fromUtf8("pushButton_browser_output"))
        self.gridLayout_2.addWidget(self.pushButton_browser_output, 5, 6, 1, 1)
        self.lineEdit_segmentation = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_segmentation.setObjectName(_fromUtf8("lineEdit_segmentation"))
        self.gridLayout_2.addWidget(self.lineEdit_segmentation, 1, 0, 1, 6)
#         self.label_chps_name_1 = QtGui.QLabel(self.tab_3)
#         self.label_chps_name_1.setObjectName(_fromUtf8("label_chps_name_1"))
#         self.gridLayout_2.addWidget(self.label_chps_name_1, 10, 2, 1, 1)
        self.label_classification_method = QtGui.QLabel(self.tab_3)
        self.label_classification_method.setObjectName(_fromUtf8("label_classification_method"))
        self.gridLayout_2.addWidget(self.label_classification_method, 2, 0, 1, 3)
        self.radioButton_rf = QtGui.QRadioButton(self.tab_3)
        self.radioButton_rf.setEnabled(True)
        self.radioButton_rf.setMouseTracking(True)
        self.radioButton_rf.setChecked(True)
        self.radioButton_rf.setObjectName(_fromUtf8("radioButton_rf"))
        self.gridLayout_2.addWidget(self.radioButton_rf, 3, 0, 1, 2)
#         self.label_chps_name_3 = QtGui.QLabel(self.tab_3)
#         self.label_chps_name_3.setObjectName(_fromUtf8("label_chps_name_3"))
#         self.gridLayout_2.addWidget(self.label_chps_name_3, 16, 2, 1, 1)
#         self.lineEdit_fieldname_1 = QtGui.QLineEdit(self.tab_3)
#         self.lineEdit_fieldname_1.setObjectName(_fromUtf8("lineEdit_fieldname_1"))
#         self.gridLayout_2.addWidget(self.lineEdit_fieldname_1, 10, 3, 1, 1)
        self.pushButton_browser_segmentation = QtGui.QPushButton(self.tab_3)
        self.pushButton_browser_segmentation.setObjectName(_fromUtf8("pushButton_browser_segmentation"))
        self.gridLayout_2.addWidget(self.pushButton_browser_segmentation, 1, 6, 1, 1)
        self.label_chps_type_0 = QtGui.QLabel(self.tab_3)
        self.label_chps_type_0.setObjectName(_fromUtf8("label_chps_type_0"))
        self.gridLayout_2.addWidget(self.label_chps_type_0, 8, 0, 1, 1)
#         self.label_chps_2 = QtGui.QLabel(self.tab_3)
#         self.label_chps_2.setObjectName(_fromUtf8("label_chps_2"))
#         self.gridLayout_2.addWidget(self.label_chps_2, 13, 0, 2, 2)
#         self.lineEdit_fieldname_4 = QtGui.QLineEdit(self.tab_3)
#         self.lineEdit_fieldname_4.setObjectName(_fromUtf8("lineEdit_fieldname_4"))
#         self.gridLayout_2.addWidget(self.lineEdit_fieldname_4, 16, 6, 1, 1)
#         self.comboBox_fieldname_13 = QtGui.QComboBox(self.tab_3)
#         self.comboBox_fieldname_13.setObjectName(_fromUtf8("comboBox_fieldname_13"))
#         self.gridLayout_2.addWidget(self.comboBox_fieldname_13, 17, 3, 1, 1)
        self.label_ouput_fieldname = QtGui.QLabel(self.tab_3)
        self.label_ouput_fieldname.setObjectName(_fromUtf8("label_ouput_fieldname"))
        self.gridLayout_2.addWidget(self.label_ouput_fieldname, 6, 0, 1, 4)
#         self.comboBox_fieldname_4 = QtGui.QComboBox(self.tab_3)
#         self.comboBox_fieldname_4.setObjectName(_fromUtf8("comboBox_fieldname_4"))
#         self.gridLayout_2.addWidget(self.comboBox_fieldname_4, 17, 6, 1, 1)
        self.label_id_fieldname = QtGui.QLabel(self.tab_3)
        self.label_id_fieldname.setObjectName(_fromUtf8("label_id_fieldname"))
        self.gridLayout_2.addWidget(self.label_id_fieldname, 7, 1, 1, 1)
#         self.lineEdit_fieldname_2 = QtGui.QLineEdit(self.tab_3)
#         self.lineEdit_fieldname_2.setObjectName(_fromUtf8("lineEdit_fieldname_2"))
#         self.gridLayout_2.addWidget(self.lineEdit_fieldname_2, 13, 4, 1, 1)
#         self.comboBox_fieldname_2 = QtGui.QComboBox(self.tab_3)
#         self.comboBox_fieldname_2.setObjectName(_fromUtf8("comboBox_fieldname_2"))
#         self.gridLayout_2.addWidget(self.comboBox_fieldname_2, 14, 4, 1, 1)
        self.checkBox_classifier_1 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_classifier_1.setObjectName(_fromUtf8("checkBox_classifier_1"))
        self.gridLayout_2.addWidget(self.checkBox_classifier_1, 9, 0, 1, 5)
#         self.label_chps_3 = QtGui.QLabel(self.tab_3)
#         self.label_chps_3.setObjectName(_fromUtf8("label_chps_3"))
#         self.gridLayout_2.addWidget(self.label_chps_3, 16, 0, 2, 2)
#         self.comboBox_fieldname_1 = QtGui.QComboBox(self.tab_3)
#         self.comboBox_fieldname_1.setObjectName(_fromUtf8("comboBox_fieldname_1"))
#         self.gridLayout_2.addWidget(self.comboBox_fieldname_1, 11, 3, 1, 1)
#         self.label_chps_1 = QtGui.QLabel(self.tab_3)
#         self.label_chps_1.setObjectName(_fromUtf8("label_chps_1"))
#         self.gridLayout_2.addWidget(self.label_chps_1, 10, 0, 2, 2)
#         self.label_chps_type_1 = QtGui.QLabel(self.tab_3)
#         self.label_chps_type_1.setObjectName(_fromUtf8("label_chps_type_1"))
#         self.gridLayout_2.addWidget(self.label_chps_type_1, 11, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)
        PHYMOBAT.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PHYMOBAT)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 25))
        self.menubar.setDefaultUp(True)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setTearOffEnabled(True)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuAide = QtGui.QMenu(self.menubar)
        self.menuAide.setObjectName(_fromUtf8("menuAide"))
        self.menuMode = QtGui.QMenu(self.menubar)
        self.menuMode.setObjectName(_fromUtf8("menuMode"))
        PHYMOBAT.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(PHYMOBAT)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        PHYMOBAT.setStatusBar(self.statusbar)
        self.actionOuvrir = QtGui.QAction(PHYMOBAT)
        self.actionOuvrir.setObjectName(_fromUtf8("actionOuvrir"))
        self.actionSauver = QtGui.QAction(PHYMOBAT)
        self.actionSauver.setObjectName(_fromUtf8("actionSauver"))
        self.actionQuiter = QtGui.QAction(PHYMOBAT)
        self.actionQuiter.setObjectName(_fromUtf8("actionQuiter"))
        self.actionAide_de_PHYMOBAT = QtGui.QAction(PHYMOBAT)
        self.actionAide_de_PHYMOBAT.setObjectName(_fromUtf8("actionAide_de_PHYMOBAT"))
        self.actionA_propos_de_PHYMOBAT = QtGui.QAction(PHYMOBAT)
        self.actionA_propos_de_PHYMOBAT.setObjectName(_fromUtf8("actionA_propos_de_PHYMOBAT"))
        self.actionMode_Simplifi = QtGui.QAction(PHYMOBAT)
        self.actionMode_Simplifi.setObjectName(_fromUtf8("actionMode_Simplifi"))
        self.actionMode_expert = QtGui.QAction(PHYMOBAT)
        self.actionMode_expert.setObjectName(_fromUtf8("actionMode_expert"))
        self.menuMenu.addAction(self.actionOuvrir)
        self.menuMenu.addAction(self.actionSauver)
        self.menuMenu.addAction(self.actionQuiter)
        self.menuAide.addAction(self.actionAide_de_PHYMOBAT)
        self.menuAide.addAction(self.actionA_propos_de_PHYMOBAT)
        self.menuMode.addAction(self.actionMode_Simplifi)
        self.menuMode.addAction(self.actionMode_expert)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())

        self.retranslateUi(PHYMOBAT)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PHYMOBAT)
        PHYMOBAT.setTabOrder(self.tabWidget, self.lineEdit_principal_folder)
        PHYMOBAT.setTabOrder(self.lineEdit_principal_folder, self.pushButton_browser_principal_folder)
        PHYMOBAT.setTabOrder(self.pushButton_browser_principal_folder, self.comboBox_captor)
        PHYMOBAT.setTabOrder(self.comboBox_captor, self.lineEdit_year_images)
        PHYMOBAT.setTabOrder(self.lineEdit_year_images, self.lineEdit_area_path)
        PHYMOBAT.setTabOrder(self.lineEdit_area_path, self.pushButton_browser_area_path)
        PHYMOBAT.setTabOrder(self.pushButton_browser_area_path, self.checkBox_listing)
        PHYMOBAT.setTabOrder(self.checkBox_listing, self.checkBox_download)
        PHYMOBAT.setTabOrder(self.checkBox_download, self.lineEdit_user)
        PHYMOBAT.setTabOrder(self.lineEdit_user, self.lineEdit_password)
        PHYMOBAT.setTabOrder(self.lineEdit_password, self.checkBox_processing)
        PHYMOBAT.setTabOrder(self.checkBox_processing, self.checkBox_MNT)
        PHYMOBAT.setTabOrder(self.checkBox_MNT, self.lineEdit_MNT)
        PHYMOBAT.setTabOrder(self.lineEdit_MNT, self.pushButton_browser_MNT)
        PHYMOBAT.setTabOrder(self.pushButton_browser_MNT, self.checkBox_VHRS)
        PHYMOBAT.setTabOrder(self.checkBox_VHRS, self.lineEdit_VHRS)
        PHYMOBAT.setTabOrder(self.lineEdit_VHRS, self.pushButton_browser_VHRS)
        PHYMOBAT.setTabOrder(self.pushButton_browser_VHRS, self.lineEdit_sample_path)
        PHYMOBAT.setTabOrder(self.lineEdit_sample_path, self.pushButton_browser_sample_path)
        PHYMOBAT.setTabOrder(self.pushButton_browser_sample_path, self.lineEdit_select_sample_fieldname_1)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_fieldname_1, self.lineEdit_select_sample_fieldname_2)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_fieldname_2, self.lineEdit_select_sample_class_1)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_class_1, self.lineEdit_select_sample_class_2)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_class_2, self.lineEdit_select_sample_nb_poly)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_nb_poly, self.checkBox_img_sample)
        PHYMOBAT.setTabOrder(self.checkBox_img_sample, self.lineEdit_img_sample)
        PHYMOBAT.setTabOrder(self.lineEdit_img_sample, self.pushButton_img_sample)
        PHYMOBAT.setTabOrder(self.pushButton_img_sample, self.checkBox_RPG)
        PHYMOBAT.setTabOrder(self.checkBox_RPG, self.pushButton_clear_sample)
        PHYMOBAT.setTabOrder(self.pushButton_clear_sample, self.pushButton_add_sample)
        PHYMOBAT.setTabOrder(self.pushButton_add_sample, self.plainTextEdit_sample)
        PHYMOBAT.setTabOrder(self.plainTextEdit_sample, self.checkBox_threshold)
        PHYMOBAT.setTabOrder(self.checkBox_threshold, self.lineEdit_segmentation)
        PHYMOBAT.setTabOrder(self.lineEdit_segmentation, self.pushButton_browser_segmentation)
        PHYMOBAT.setTabOrder(self.pushButton_browser_segmentation, self.radioButton_rf)
        PHYMOBAT.setTabOrder(self.radioButton_rf, self.radioButton_s)
        PHYMOBAT.setTabOrder(self.radioButton_s, self.lineEdit_output)
        PHYMOBAT.setTabOrder(self.lineEdit_output, self.pushButton_browser_output)
        PHYMOBAT.setTabOrder(self.pushButton_browser_output, self.checkBox_classifier_1)
        PHYMOBAT.setTabOrder(self.checkBox_classifier_1, self.checkBox_classifier_2)
        PHYMOBAT.setTabOrder(self.checkBox_classifier_2, self.checkBox_classifier_3)
        PHYMOBAT.setTabOrder(self.checkBox_classifier_3, self.checkBox_multiprocess)
#         PHYMOBAT.setTabOrder(self.checkBox_classifier_1, self.comboBox_fieldname_1)
#         PHYMOBAT.setTabOrder(self.comboBox_fieldname_1, self.checkBox_classifier_2)
#         PHYMOBAT.setTabOrder(self.checkBox_classifier_2, self.lineEdit_fieldname_12)
#         PHYMOBAT.setTabOrder(self.lineEdit_fieldname_12, self.comboBox_fieldname_12)
#         PHYMOBAT.setTabOrder(self.comboBox_fieldname_12, self.lineEdit_fieldname_2)
#         PHYMOBAT.setTabOrder(self.lineEdit_fieldname_2, self.comboBox_fieldname_2)
#         PHYMOBAT.setTabOrder(self.comboBox_fieldname_2, self.checkBox_classifier_3)
#         PHYMOBAT.setTabOrder(self.checkBox_classifier_3, self.lineEdit_fieldname_13)
#         PHYMOBAT.setTabOrder(self.lineEdit_fieldname_13, self.comboBox_fieldname_13)
#         PHYMOBAT.setTabOrder(self.comboBox_fieldname_13, self.lineEdit_fieldname_23)
#         PHYMOBAT.setTabOrder(self.lineEdit_fieldname_23, self.comboBox_fieldname_23)
#         PHYMOBAT.setTabOrder(self.comboBox_fieldname_23, self.lineEdit_fieldname_3)
#         PHYMOBAT.setTabOrder(self.lineEdit_fieldname_3, self.comboBox_fieldname_3)
#         PHYMOBAT.setTabOrder(self.comboBox_fieldname_3, self.lineEdit_fieldname_4)
#         PHYMOBAT.setTabOrder(self.lineEdit_fieldname_4, self.comboBox_fieldname_4)
#         PHYMOBAT.setTabOrder(self.comboBox_fieldname_4, self.checkBox_multiprocess)
        PHYMOBAT.setTabOrder(self.checkBox_multiprocess, self.buttonBox)

    def retranslateUi(self, PHYMOBAT):
        PHYMOBAT.setWindowTitle(_translate("PHYMOBAT", "PHYMOBATe 2.0", None))
        self.checkBox_multiprocess.setText(_translate("PHYMOBAT", "Multi-processing", None))
        self.pushButton_browser_area_path.setText(_translate("PHYMOBAT", "...", None))
        self.pushButton_browser_principal_folder.setText(_translate("PHYMOBAT", "...", None))
        self.label_principal_folder.setText(_translate("PHYMOBAT", "Chemin du dossier principal", None))
        self.label_area_path.setText(_translate("PHYMOBAT", "Emprise de la zone (shp)", None))
        self.checkBox_download.setText(_translate("PHYMOBAT", "Télécharger", None))
        self.lineEdit_password.setToolTip(_translate("PHYMOBAT", "Mot de passe masqué", None))
        self.pushButton_browser_VHRS.setText(_translate("PHYMOBAT", "...", None))
        self.label_id_theia.setText(_translate("PHYMOBAT", "Identifiant Theia :", None))
        self.label_password.setText(_translate("PHYMOBAT", "Mot de passe", None))
        self.label_user.setText(_translate("PHYMOBAT", "Utilisateur :", None))
        self.checkBox_VHRS.setText(_translate("PHYMOBAT", "Images THRS", None))
        self.label_year_images.setText(_translate("PHYMOBAT", "Année des images", None))
        self.checkBox_listing.setText(_translate("PHYMOBAT", "Images disponibles :", None))
        self.comboBox_captor.setItemText(0, _translate("PHYMOBAT", "Landsat", None))
        self.comboBox_captor.setItemText(1, _translate("PHYMOBAT", "SpotWorldHeritage", None))
        self.label_captor.setText(_translate("PHYMOBAT", "Capteur des images à télécharger", None))
        self.checkBox_MNT.setText(_translate("PHYMOBAT", "MNT", None))
        self.label_listing.setText(_translate("PHYMOBAT", "0", None))
        self.pushButton_browser_MNT.setText(_translate("PHYMOBAT", "...", None))
        self.checkBox_processing.setText(_translate("PHYMOBAT", "Traitement des images téléchargées", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PHYMOBAT", "Traitement images", None))
        self.pushButton_img_sample.setText(_translate("PHYMOBAT", "...", None))
        self.checkBox_RPG.setText(_translate("PHYMOBAT", "RPG", None))
        self.pushButton_clear_sample.setText(_translate("PHYMOBAT", "Effacer", None))
        self.checkBox_img_sample.setText(_translate("PHYMOBAT", "Image échantillonnée (Si \"traitement images\" n\'est pas lancé) :", None))
        self.label_select_sample_fieldname.setText(_translate("PHYMOBAT", "Champs", None))
        self.pushButton_add_sample.setText(_translate("PHYMOBAT", "Ajouter", None))
        self.plainTextEdit_sample.setPlainText(_translate("PHYMOBAT", "1 - Végétation non naturelle / Semi-naturelle\n"
"2 - Herbacés / Ligneux\n"
"3 - Ligneux denses / mixtes\n"
"\n"
"\n"
"", None))
        self.label_sample_path.setText(_translate("PHYMOBAT", "Echantillons (shp)", None))
        self.label_select_sample_nb_poly.setText(_translate("PHYMOBAT", "Nombre de polygones", None))
        self.pushButton_browser_sample_path.setText(_translate("PHYMOBAT", "...", None))
        self.label_select_sample_class.setText(_translate("PHYMOBAT", "Classes", None))
        self.label_select_sample_class_1.setText(_translate("PHYMOBAT", "      Classe 1", None))
        self.label_select_sample.setText(_translate("PHYMOBAT", "Sélection par classe de 2", None))
        self.label_select_sample_class_2.setText(_translate("PHYMOBAT", "       Classe 2", None))
        self.checkBox_threshold.setText(_translate("PHYMOBAT", "Déterminer les seuils optimaux", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PHYMOBAT", "Echantillons", None))
        self.label_area_fieldtype.setText(_translate("PHYMOBAT", "Real", None))
        self.label_area_fieldname.setText(_translate("PHYMOBAT", "AREA", None))
#         self.label_chps_type_2.setText(_translate("PHYMOBAT", "Type :", None))
        self.checkBox_classifier_2.setText(_translate("PHYMOBAT", "Classification que sur les deux premiers niveaux", None))
#         self.label_chps_type_3.setText(_translate("PHYMOBAT", "Type :", None))
        self.label_ouput.setText(_translate("PHYMOBAT", "Fichier de sortie (shp)", None))
        self.label_chps_name_0.setText(_translate("PHYMOBAT", "Nom :", None))
        self.label_segmentation.setText(_translate("PHYMOBAT", "Segmentation (shp)", None))
        self.label_id_fieldtype.setText(_translate("PHYMOBAT", "String", None))
        self.checkBox_classifier_3.setText(_translate("PHYMOBAT", "Classification complète (sur les trois niveaux)", None))
#         self.label_chps_name_2.setText(_translate("PHYMOBAT", "Nom :", None))
        self.radioButton_s.setText(_translate("PHYMOBAT", "Arbre de décision (Seath)", None))
        self.pushButton_browser_output.setText(_translate("PHYMOBAT", "...", None))
#         self.label_chps_name_1.setText(_translate("PHYMOBAT", "Nom :", None))
        self.label_classification_method.setText(_translate("PHYMOBAT", "Méthode de classification :", None))
        self.radioButton_rf.setText(_translate("PHYMOBAT", "Random Forest", None))
#         self.label_chps_name_3.setText(_translate("PHYMOBAT", "Nom :", None))
        self.pushButton_browser_segmentation.setText(_translate("PHYMOBAT", "...", None))
        self.label_chps_type_0.setText(_translate("PHYMOBAT", "Type :", None))
#         self.label_chps_2.setText(_translate("PHYMOBAT", "    Champs\n"
# " des entités", None))
        self.label_ouput_fieldname.setText(_translate("PHYMOBAT", "Champs du fichier de sortie pré-définis :", None))
        self.label_id_fieldname.setText(_translate("PHYMOBAT", "ID", None))
        self.checkBox_classifier_1.setText(_translate("PHYMOBAT", "Classification que sur le premier niveau", None))
#         self.label_chps_3.setText(_translate("PHYMOBAT", "    Champs\n"
# " des entités", None))
#         self.label_chps_1.setText(_translate("PHYMOBAT", "    Champs\n"
# " des entités", None))
#         self.label_chps_type_1.setText(_translate("PHYMOBAT", "Type :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("PHYMOBAT", "Classification", None))
        self.menuMenu.setTitle(_translate("PHYMOBAT", "Menu", None))
        self.menuAide.setTitle(_translate("PHYMOBAT", "Aide", None))
        self.menuMode.setTitle(_translate("PHYMOBAT", "Mode", None))
        self.actionOuvrir.setText(_translate("PHYMOBAT", "Ouvrir", None))
        self.actionSauver.setText(_translate("PHYMOBAT", "Sauver", None))
        self.actionQuiter.setText(_translate("PHYMOBAT", "Quiter", None))
        self.actionAide_de_PHYMOBAT.setText(_translate("PHYMOBAT", "Aide de PHYMOBAT", None))
        self.actionA_propos_de_PHYMOBAT.setText(_translate("PHYMOBAT", "A propos de PHYMOBAT", None))
        self.actionMode_Simplifi.setText(_translate("PHYMOBAT", "Mode Simplifié", None))
        self.actionMode_expert.setText(_translate("PHYMOBAT", "Mode Expert", None))

