# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PHYMOBATs_tab_2_0.ui'
#
# Created: Tue Sep 13 10:45:52 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PHYMOBAT(object):
    
    """
    Class to display “Simplify PHYMOBAT window”.
    """
    
    def setupUi(self, PHYMOBAT):
        PHYMOBAT.setObjectName(_fromUtf8("PHYMOBAT"))
        PHYMOBAT.resize(726, 1052)
        self.centralwidget = QtGui.QWidget(PHYMOBAT)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 5, 1, 1, 1)
        self.checkBox_multiprocess = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_multiprocess.setCheckable(True)
        self.checkBox_multiprocess.setChecked(True)
        self.checkBox_multiprocess.setAutoRepeat(False)
        self.checkBox_multiprocess.setObjectName(_fromUtf8("checkBox_multiprocess"))
        self.gridLayout_4.addWidget(self.checkBox_multiprocess, 5, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_select_sample_nb_poly_3 = QtGui.QLabel(self.frame_2)
        self.label_select_sample_nb_poly_3.setObjectName(_fromUtf8("label_select_sample_nb_poly_3"))
        self.gridLayout_3.addWidget(self.label_select_sample_nb_poly_3, 5, 5, 1, 1)
        self.label_select_sample_class_6 = QtGui.QLabel(self.frame_2)
        self.label_select_sample_class_6.setObjectName(_fromUtf8("label_select_sample_class_6"))
        self.gridLayout_3.addWidget(self.label_select_sample_class_6, 5, 0, 1, 1)
        self.label_select_sample_class_7 = QtGui.QLabel(self.frame_2)
        self.label_select_sample_class_7.setObjectName(_fromUtf8("label_select_sample_class_7"))
        self.gridLayout_3.addWidget(self.label_select_sample_class_7, 3, 2, 1, 1)
        self.lineEdit_select_sample_nb_poly_3 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_select_sample_nb_poly_3.setObjectName(_fromUtf8("lineEdit_select_sample_nb_poly_3"))
        self.gridLayout_3.addWidget(self.lineEdit_select_sample_nb_poly_3, 5, 6, 1, 1)
        self.lineEdit_select_sample_fieldname_5 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_select_sample_fieldname_5.setObjectName(_fromUtf8("lineEdit_select_sample_fieldname_5"))
        self.gridLayout_3.addWidget(self.lineEdit_select_sample_fieldname_5, 4, 2, 1, 2)
        self.pushButton_browser_sample_path_3 = QtGui.QPushButton(self.frame_2)
        self.pushButton_browser_sample_path_3.setObjectName(_fromUtf8("pushButton_browser_sample_path_3"))
        self.gridLayout_3.addWidget(self.pushButton_browser_sample_path_3, 1, 7, 2, 1)
        spacerItem = QtGui.QSpacerItem(79, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 4, 1, 1, 1)
        self.lineEdit_select_sample_class_6 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_select_sample_class_6.setObjectName(_fromUtf8("lineEdit_select_sample_class_6"))
        self.gridLayout_3.addWidget(self.lineEdit_select_sample_class_6, 5, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(79, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 5, 1, 1, 1)
        self.label_select_sample_fieldname_3 = QtGui.QLabel(self.frame_2)
        self.label_select_sample_fieldname_3.setObjectName(_fromUtf8("label_select_sample_fieldname_3"))
        self.gridLayout_3.addWidget(self.label_select_sample_fieldname_3, 4, 0, 1, 1)
        self.label_sample_path_3 = QtGui.QLabel(self.frame_2)
        self.label_sample_path_3.setObjectName(_fromUtf8("label_sample_path_3"))
        self.gridLayout_3.addWidget(self.label_sample_path_3, 0, 0, 1, 4)
        self.label_select_sample_class_8 = QtGui.QLabel(self.frame_2)
        self.label_select_sample_class_8.setObjectName(_fromUtf8("label_select_sample_class_8"))
        self.gridLayout_3.addWidget(self.label_select_sample_class_8, 3, 4, 1, 1)
        self.lineEdit_sample_path_3 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_sample_path_3.setObjectName(_fromUtf8("lineEdit_sample_path_3"))
        self.gridLayout_3.addWidget(self.lineEdit_sample_path_3, 1, 0, 2, 7)
        self.lineEdit_select_sample_fieldname_6 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_select_sample_fieldname_6.setObjectName(_fromUtf8("lineEdit_select_sample_fieldname_6"))
        self.gridLayout_3.addWidget(self.lineEdit_select_sample_fieldname_6, 4, 4, 1, 1)
        self.lineEdit_select_sample_class_5 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_select_sample_class_5.setObjectName(_fromUtf8("lineEdit_select_sample_class_5"))
        self.gridLayout_3.addWidget(self.lineEdit_select_sample_class_5, 5, 2, 1, 2)
        self.gridLayout_4.addWidget(self.frame_2, 3, 0, 1, 2)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_ouput = QtGui.QLabel(self.frame_3)
        self.label_ouput.setObjectName(_fromUtf8("label_ouput"))
        self.gridLayout_2.addWidget(self.label_ouput, 0, 0, 1, 1)
        self.lineEdit_output = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_output.setObjectName(_fromUtf8("lineEdit_output"))
        self.gridLayout_2.addWidget(self.lineEdit_output, 1, 0, 1, 1)
        self.pushButton_browser_output = QtGui.QPushButton(self.frame_3)
        self.pushButton_browser_output.setObjectName(_fromUtf8("pushButton_browser_output"))
        self.gridLayout_2.addWidget(self.pushButton_browser_output, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 4, 0, 1, 2)
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(90, 12, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 4, 1, 1, 1)
        self.pushButton_browser_sample_path = QtGui.QPushButton(self.frame_4)
        self.pushButton_browser_sample_path.setObjectName(_fromUtf8("pushButton_browser_sample_path"))
        self.gridLayout_5.addWidget(self.pushButton_browser_sample_path, 1, 6, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(82, 15, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 4, 6, 1, 1)
        self.lineEdit_select_sample_nb_poly = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_select_sample_nb_poly.setObjectName(_fromUtf8("lineEdit_select_sample_nb_poly"))
        self.gridLayout_5.addWidget(self.lineEdit_select_sample_nb_poly, 4, 5, 1, 1)
        self.label_select_sample_class_1 = QtGui.QLabel(self.frame_4)
        self.label_select_sample_class_1.setObjectName(_fromUtf8("label_select_sample_class_1"))
        self.gridLayout_5.addWidget(self.label_select_sample_class_1, 2, 2, 1, 1)
        self.label_select_sample_class_2 = QtGui.QLabel(self.frame_4)
        self.label_select_sample_class_2.setObjectName(_fromUtf8("label_select_sample_class_2"))
        self.gridLayout_5.addWidget(self.label_select_sample_class_2, 2, 3, 1, 1)
        self.label_select_sample_fieldname = QtGui.QLabel(self.frame_4)
        self.label_select_sample_fieldname.setObjectName(_fromUtf8("label_select_sample_fieldname"))
        self.gridLayout_5.addWidget(self.label_select_sample_fieldname, 3, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(90, 12, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 3, 1, 1, 1)
        self.label_select_sample_nb_poly = QtGui.QLabel(self.frame_4)
        self.label_select_sample_nb_poly.setObjectName(_fromUtf8("label_select_sample_nb_poly"))
        self.gridLayout_5.addWidget(self.label_select_sample_nb_poly, 4, 4, 1, 1)
        self.lineEdit_select_sample_class_2 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_select_sample_class_2.setObjectName(_fromUtf8("lineEdit_select_sample_class_2"))
        self.gridLayout_5.addWidget(self.lineEdit_select_sample_class_2, 4, 3, 1, 1)
        self.lineEdit_select_sample_fieldname_1 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_select_sample_fieldname_1.setObjectName(_fromUtf8("lineEdit_select_sample_fieldname_1"))
        self.gridLayout_5.addWidget(self.lineEdit_select_sample_fieldname_1, 3, 2, 1, 1)
        self.label_sample_path = QtGui.QLabel(self.frame_4)
        self.label_sample_path.setObjectName(_fromUtf8("label_sample_path"))
        self.gridLayout_5.addWidget(self.label_sample_path, 0, 0, 1, 4)
        self.lineEdit_select_sample_fieldname_2 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_select_sample_fieldname_2.setObjectName(_fromUtf8("lineEdit_select_sample_fieldname_2"))
        self.gridLayout_5.addWidget(self.lineEdit_select_sample_fieldname_2, 3, 3, 1, 1)
        self.lineEdit_sample_path = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_sample_path.setObjectName(_fromUtf8("lineEdit_sample_path"))
        self.gridLayout_5.addWidget(self.lineEdit_sample_path, 1, 0, 1, 6)
        self.lineEdit_select_sample_class_1 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_select_sample_class_1.setObjectName(_fromUtf8("lineEdit_select_sample_class_1"))
        self.gridLayout_5.addWidget(self.lineEdit_select_sample_class_1, 4, 2, 1, 1)
        self.label_select_sample_class = QtGui.QLabel(self.frame_4)
        self.label_select_sample_class.setObjectName(_fromUtf8("label_select_sample_class"))
        self.gridLayout_5.addWidget(self.label_select_sample_class, 4, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_4, 1, 0, 1, 2)
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_select_sample_class_4 = QtGui.QLabel(self.frame_5)
        self.label_select_sample_class_4.setObjectName(_fromUtf8("label_select_sample_class_4"))
        self.gridLayout_6.addWidget(self.label_select_sample_class_4, 4, 0, 1, 1)
        self.lineEdit_sample_path_2 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_sample_path_2.setObjectName(_fromUtf8("lineEdit_sample_path_2"))
        self.gridLayout_6.addWidget(self.lineEdit_sample_path_2, 1, 0, 1, 6)
        self.label_select_sample_fieldname_2 = QtGui.QLabel(self.frame_5)
        self.label_select_sample_fieldname_2.setObjectName(_fromUtf8("label_select_sample_fieldname_2"))
        self.gridLayout_6.addWidget(self.label_select_sample_fieldname_2, 3, 0, 1, 1)
        self.lineEdit_select_sample_class_4 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_select_sample_class_4.setObjectName(_fromUtf8("lineEdit_select_sample_class_4"))
        self.gridLayout_6.addWidget(self.lineEdit_select_sample_class_4, 4, 3, 1, 1)
        self.label_select_sample_nb_poly_2 = QtGui.QLabel(self.frame_5)
        self.label_select_sample_nb_poly_2.setObjectName(_fromUtf8("label_select_sample_nb_poly_2"))
        self.gridLayout_6.addWidget(self.label_select_sample_nb_poly_2, 4, 4, 1, 1)
        self.label_select_sample_class_3 = QtGui.QLabel(self.frame_5)
        self.label_select_sample_class_3.setObjectName(_fromUtf8("label_select_sample_class_3"))
        self.gridLayout_6.addWidget(self.label_select_sample_class_3, 2, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(76, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 4, 1, 1, 1)
        self.lineEdit_select_sample_fieldname_3 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_select_sample_fieldname_3.setObjectName(_fromUtf8("lineEdit_select_sample_fieldname_3"))
        self.gridLayout_6.addWidget(self.lineEdit_select_sample_fieldname_3, 3, 2, 1, 1)
        self.pushButton_browser_sample_path_2 = QtGui.QPushButton(self.frame_5)
        self.pushButton_browser_sample_path_2.setObjectName(_fromUtf8("pushButton_browser_sample_path_2"))
        self.gridLayout_6.addWidget(self.pushButton_browser_sample_path_2, 1, 6, 1, 1)
        self.lineEdit_select_sample_fieldname_4 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_select_sample_fieldname_4.setObjectName(_fromUtf8("lineEdit_select_sample_fieldname_4"))
        self.gridLayout_6.addWidget(self.lineEdit_select_sample_fieldname_4, 3, 3, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(76, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 3, 1, 1, 1)
        self.label_sample_path_2 = QtGui.QLabel(self.frame_5)
        self.label_sample_path_2.setObjectName(_fromUtf8("label_sample_path_2"))
        self.gridLayout_6.addWidget(self.label_sample_path_2, 0, 0, 1, 3)
        self.lineEdit_select_sample_nb_poly_2 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_select_sample_nb_poly_2.setObjectName(_fromUtf8("lineEdit_select_sample_nb_poly_2"))
        self.gridLayout_6.addWidget(self.lineEdit_select_sample_nb_poly_2, 4, 5, 1, 1)
        self.lineEdit_select_sample_class_3 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_select_sample_class_3.setObjectName(_fromUtf8("lineEdit_select_sample_class_3"))
        self.gridLayout_6.addWidget(self.lineEdit_select_sample_class_3, 4, 2, 1, 1)
        self.label_select_sample_class_5 = QtGui.QLabel(self.frame_5)
        self.label_select_sample_class_5.setObjectName(_fromUtf8("label_select_sample_class_5"))
        self.gridLayout_6.addWidget(self.label_select_sample_class_5, 2, 3, 1, 1)
        self.gridLayout_4.addWidget(self.frame_5, 2, 0, 1, 2)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_principal_folder = QtGui.QLabel(self.frame)
        self.label_principal_folder.setObjectName(_fromUtf8("label_principal_folder"))
        self.gridLayout.addWidget(self.label_principal_folder, 0, 0, 1, 2)
        self.lineEdit_principal_folder = QtGui.QLineEdit(self.frame)
        self.lineEdit_principal_folder.setObjectName(_fromUtf8("lineEdit_principal_folder"))
        self.gridLayout.addWidget(self.lineEdit_principal_folder, 1, 0, 1, 5)
        self.pushButton_browser_principal_folder = QtGui.QPushButton(self.frame)
        self.pushButton_browser_principal_folder.setObjectName(_fromUtf8("pushButton_browser_principal_folder"))
        self.gridLayout.addWidget(self.pushButton_browser_principal_folder, 1, 5, 1, 1)
        self.label_year_images = QtGui.QLabel(self.frame)
        self.label_year_images.setObjectName(_fromUtf8("label_year_images"))
        self.gridLayout.addWidget(self.label_year_images, 2, 0, 1, 1)
        self.lineEdit_year_images = QtGui.QLineEdit(self.frame)
        self.lineEdit_year_images.setObjectName(_fromUtf8("lineEdit_year_images"))
        self.gridLayout.addWidget(self.lineEdit_year_images, 2, 1, 1, 2)
        self.label_ex_period = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.label_ex_period.setFont(font)
        self.label_ex_period.setObjectName(_fromUtf8("label_ex_period"))
        self.gridLayout.addWidget(self.label_ex_period, 2, 3, 1, 3)        
        self.label_area_path = QtGui.QLabel(self.frame)
        self.label_area_path.setObjectName(_fromUtf8("label_area_path"))
        self.gridLayout.addWidget(self.label_area_path, 3, 0, 1, 2)
        self.lineEdit_area_path = QtGui.QLineEdit(self.frame)
        self.lineEdit_area_path.setObjectName(_fromUtf8("lineEdit_area_path"))
        self.gridLayout.addWidget(self.lineEdit_area_path, 4, 0, 1, 5)
        self.pushButton_browser_area_path = QtGui.QPushButton(self.frame)
        self.pushButton_browser_area_path.setObjectName(_fromUtf8("pushButton_browser_area_path"))
        self.gridLayout.addWidget(self.pushButton_browser_area_path, 4, 5, 1, 1)
        self.label_id_theia = QtGui.QLabel(self.frame)
        self.label_id_theia.setObjectName(_fromUtf8("label_id_theia"))
        self.gridLayout.addWidget(self.label_id_theia, 5, 0, 1, 1)
        self.label_user = QtGui.QLabel(self.frame)
        self.label_user.setObjectName(_fromUtf8("label_user"))
        self.gridLayout.addWidget(self.label_user, 6, 0, 1, 1)
        self.lineEdit_user = QtGui.QLineEdit(self.frame)
        self.lineEdit_user.setObjectName(_fromUtf8("lineEdit_user"))
        self.gridLayout.addWidget(self.lineEdit_user, 6, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(73, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 6, 2, 1, 1)
        self.label_password = QtGui.QLabel(self.frame)
        self.label_password.setObjectName(_fromUtf8("label_password"))
        self.gridLayout.addWidget(self.label_password, 6, 3, 1, 1)
        self.lineEdit_password = QtGui.QLineEdit(self.frame)
        self.lineEdit_password.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_password.setObjectName(_fromUtf8("lineEdit_password"))
        self.gridLayout.addWidget(self.lineEdit_password, 6, 4, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 6, 5, 1, 1)
        self.checkBox_MNT = QtGui.QLabel(self.frame)
        self.checkBox_MNT.setObjectName(_fromUtf8("checkBox_MNT"))
        self.gridLayout.addWidget(self.checkBox_MNT, 7, 0, 1, 1)
        self.lineEdit_MNT = QtGui.QLineEdit(self.frame)
        self.lineEdit_MNT.setObjectName(_fromUtf8("lineEdit_MNT"))
#         self.lineEdit_MNT.setEnabled(False)
        self.gridLayout.addWidget(self.lineEdit_MNT, 8, 0, 1, 5)
        self.pushButton_browser_MNT = QtGui.QPushButton(self.frame)
        self.pushButton_browser_MNT.setObjectName(_fromUtf8("pushButton_browser_MNT"))
#         self.pushButton_browser_MNT.setEnabled(False)
        self.gridLayout.addWidget(self.pushButton_browser_MNT, 8, 5, 1, 1)
        self.checkBox_VHRS = QtGui.QLabel(self.frame)
        self.checkBox_VHRS.setObjectName(_fromUtf8("checkBox_VHRS"))
        self.gridLayout.addWidget(self.checkBox_VHRS, 9, 0, 1, 1)
        self.lineEdit_VHRS = QtGui.QLineEdit(self.frame)
        self.lineEdit_VHRS.setObjectName(_fromUtf8("lineEdit_VHRS"))
        self.gridLayout.addWidget(self.lineEdit_VHRS, 10, 0, 1, 5)
        self.pushButton_browser_VHRS = QtGui.QPushButton(self.frame)
        self.pushButton_browser_VHRS.setObjectName(_fromUtf8("pushButton_browser_VHRS"))
        self.gridLayout.addWidget(self.pushButton_browser_VHRS, 10, 5, 1, 1)
        self.label_segmentation = QtGui.QLabel(self.frame)
        self.label_segmentation.setObjectName(_fromUtf8("label_segmentation"))
        self.gridLayout.addWidget(self.label_segmentation, 11, 0, 1, 2)
        self.lineEdit_segmentation = QtGui.QLineEdit(self.frame)
        self.lineEdit_segmentation.setObjectName(_fromUtf8("lineEdit_segmentation"))
        self.gridLayout.addWidget(self.lineEdit_segmentation, 12, 0, 1, 5)
        self.pushButton_browser_segmentation = QtGui.QPushButton(self.frame)
        self.pushButton_browser_segmentation.setObjectName(_fromUtf8("pushButton_browser_segmentation"))
        self.gridLayout.addWidget(self.pushButton_browser_segmentation, 12, 5, 1, 1)
        self.proxy = QtGui.QPushButton(self.frame)
        self.proxy.setObjectName(_fromUtf8("proxy"))
        self.gridLayout.addWidget(self.proxy, 6, 5, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 2)
        PHYMOBAT.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PHYMOBAT)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 726, 25))
        self.menubar.setDefaultUp(True)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setTearOffEnabled(True)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuAide = QtGui.QMenu(self.menubar)
        self.menuAide.setObjectName(_fromUtf8("menuAide"))
        self.menuMode = QtGui.QMenu(self.menubar)
        self.menuMode.setObjectName(_fromUtf8("menuMode"))
        PHYMOBAT.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(PHYMOBAT)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        PHYMOBAT.setStatusBar(self.statusbar)
        self.actionOuvrir = QtGui.QAction(PHYMOBAT)
        self.actionOuvrir.setObjectName(_fromUtf8("actionOuvrir"))
        self.actionSauver = QtGui.QAction(PHYMOBAT)
        self.actionSauver.setObjectName(_fromUtf8("actionSauver"))
        self.actionQuiter = QtGui.QAction(PHYMOBAT)
        self.actionQuiter.setObjectName(_fromUtf8("actionQuiter"))
        self.actionAide_de_PHYMOBAT = QtGui.QAction(PHYMOBAT)
        self.actionAide_de_PHYMOBAT.setObjectName(_fromUtf8("actionAide_de_PHYMOBAT"))
        self.actionA_propos_de_PHYMOBAT = QtGui.QAction(PHYMOBAT)
        self.actionA_propos_de_PHYMOBAT.setObjectName(_fromUtf8("actionA_propos_de_PHYMOBAT"))
        self.actionMode_Simplifi = QtGui.QAction(PHYMOBAT)
        self.actionMode_Simplifi.setObjectName(_fromUtf8("actionMode_Simplifi"))
        self.actionMode_expert = QtGui.QAction(PHYMOBAT)
        self.actionMode_expert.setObjectName(_fromUtf8("actionMode_expert"))
        self.menuMenu.addAction(self.actionOuvrir)
        self.menuMenu.addAction(self.actionSauver)
        self.menuMenu.addAction(self.actionQuiter)
        self.menuAide.addAction(self.actionAide_de_PHYMOBAT)
        self.menuAide.addAction(self.actionA_propos_de_PHYMOBAT)
        self.menuMode.addAction(self.actionMode_Simplifi)
        self.menuMode.addAction(self.actionMode_expert)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())

        self.retranslateUi(PHYMOBAT)
        QtCore.QMetaObject.connectSlotsByName(PHYMOBAT)
        PHYMOBAT.setTabOrder(self.checkBox_multiprocess, self.buttonBox)
        PHYMOBAT.setTabOrder(self.buttonBox, self.lineEdit_principal_folder)
        PHYMOBAT.setTabOrder(self.lineEdit_principal_folder, self.pushButton_browser_principal_folder)
        PHYMOBAT.setTabOrder(self.pushButton_browser_principal_folder, self.lineEdit_year_images)
        PHYMOBAT.setTabOrder(self.lineEdit_year_images, self.lineEdit_area_path)
        PHYMOBAT.setTabOrder(self.lineEdit_area_path, self.pushButton_browser_area_path)
        PHYMOBAT.setTabOrder(self.pushButton_browser_area_path, self.lineEdit_user)
        PHYMOBAT.setTabOrder(self.lineEdit_user, self.lineEdit_password)
        PHYMOBAT.setTabOrder(self.lineEdit_password, self.lineEdit_MNT)
        PHYMOBAT.setTabOrder(self.lineEdit_MNT, self.pushButton_browser_MNT)
        PHYMOBAT.setTabOrder(self.pushButton_browser_MNT, self.lineEdit_VHRS)
        PHYMOBAT.setTabOrder(self.lineEdit_VHRS, self.pushButton_browser_VHRS)
        PHYMOBAT.setTabOrder(self.pushButton_browser_VHRS, self.lineEdit_segmentation)
        PHYMOBAT.setTabOrder(self.lineEdit_segmentation, self.pushButton_browser_segmentation)
        PHYMOBAT.setTabOrder(self.pushButton_browser_segmentation, self.lineEdit_sample_path)
        PHYMOBAT.setTabOrder(self.lineEdit_sample_path, self.pushButton_browser_sample_path)
        PHYMOBAT.setTabOrder(self.pushButton_browser_sample_path, self.lineEdit_select_sample_fieldname_1)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_fieldname_1, self.lineEdit_select_sample_fieldname_2)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_fieldname_2, self.lineEdit_select_sample_class_1)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_class_1, self.lineEdit_select_sample_class_2)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_class_2, self.lineEdit_select_sample_nb_poly)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_nb_poly, self.lineEdit_sample_path_2)
        PHYMOBAT.setTabOrder(self.lineEdit_sample_path_2, self.pushButton_browser_sample_path_2)
        PHYMOBAT.setTabOrder(self.pushButton_browser_sample_path_2, self.lineEdit_select_sample_fieldname_3)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_fieldname_3, self.lineEdit_select_sample_fieldname_4)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_fieldname_4, self.lineEdit_select_sample_class_3)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_class_3, self.lineEdit_select_sample_class_4)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_class_4, self.lineEdit_select_sample_nb_poly_2)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_nb_poly_2, self.lineEdit_sample_path_3)
        PHYMOBAT.setTabOrder(self.lineEdit_sample_path_3, self.pushButton_browser_sample_path_3)
        PHYMOBAT.setTabOrder(self.pushButton_browser_sample_path_3, self.lineEdit_select_sample_fieldname_5)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_fieldname_5, self.lineEdit_select_sample_fieldname_6)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_fieldname_6, self.lineEdit_select_sample_class_5)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_class_5, self.lineEdit_select_sample_class_6)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_class_6, self.lineEdit_select_sample_nb_poly_3)
        PHYMOBAT.setTabOrder(self.lineEdit_select_sample_nb_poly_3, self.lineEdit_output)
        PHYMOBAT.setTabOrder(self.lineEdit_output, self.pushButton_browser_output)

    def retranslateUi(self, PHYMOBAT):
        PHYMOBAT.setWindowTitle(_translate("PHYMOBAT", "PHYMOBATs 3.0", None))
        self.checkBox_multiprocess.setText(_translate("PHYMOBAT", "Multi-processing", None))
        self.label_select_sample_nb_poly_3.setText(_translate("PHYMOBAT", "<html><head/><body><p>Nbre de polygones</p></body></html>", None))
        self.label_select_sample_class_6.setText(_translate("PHYMOBAT", "Classes", None))
        self.label_select_sample_class_7.setText(_translate("PHYMOBAT", "<html><head/><body><p align=\"center\">Ligneux denses</p></body></html>", None))
        self.lineEdit_select_sample_nb_poly_3.setText(_translate("PHYMOBAT", "20", None))
        self.lineEdit_select_sample_fieldname_5.setToolTip(_translate("PHYMOBAT", "Nom du champs qui contient la classe Ligneux denses", None))
        self.pushButton_browser_sample_path_3.setText(_translate("PHYMOBAT", "...", None))
        self.lineEdit_select_sample_class_6.setToolTip(_translate("PHYMOBAT", "Intitulé de la classe dans le shapefile", None))
        self.label_select_sample_fieldname_3.setText(_translate("PHYMOBAT", "Champs", None))
        self.label_sample_path_3.setText(_translate("PHYMOBAT", "Echantillons Ligneux denses / mixtes", None))
        self.label_select_sample_class_8.setText(_translate("PHYMOBAT", "<html><head/><body><p align=\"center\">Ligneux mixtes</p></body></html>", None))
        self.lineEdit_sample_path_3.setToolTip(_translate("PHYMOBAT", "Chemin d\'accès au shapefile des échantillons de Ligneux", None))
        self.lineEdit_select_sample_fieldname_6.setToolTip(_translate("PHYMOBAT", "Nom du champs qui contient la classe Ligneux mixtes", None))
        self.lineEdit_select_sample_class_5.setToolTip(_translate("PHYMOBAT", "Intitulé de la classe dans le shapefile", None))
        self.label_ouput.setText(_translate("PHYMOBAT", "Fichier de sortie (shp)", None))
        self.lineEdit_output.setToolTip(_translate("PHYMOBAT", "Chemin du fichier de la cartographie finale", None))
        self.pushButton_browser_output.setText(_translate("PHYMOBAT", "...", None))
        self.pushButton_browser_sample_path.setText(_translate("PHYMOBAT", "...", None))
        self.lineEdit_select_sample_nb_poly.setText(_translate("PHYMOBAT", "100", None))
        self.label_select_sample_class_1.setText(_translate("PHYMOBAT", "<html><head/><body><p align=\"center\">Non naturelle</p></body></html>", None))
        self.label_select_sample_class_2.setText(_translate("PHYMOBAT", "<html><head/><body><p align=\"center\">Semi-naturelle</p></body></html>", None))
        self.label_select_sample_fieldname.setText(_translate("PHYMOBAT", "Champs", None))
        self.label_select_sample_nb_poly.setText(_translate("PHYMOBAT", "<html><head/><body><p>Nbre de polygones</p></body></html>", None))
        self.lineEdit_select_sample_class_2.setToolTip(_translate("PHYMOBAT", "Intitulé de la classe dans le shapefile", None))
        self.lineEdit_select_sample_fieldname_1.setToolTip(_translate("PHYMOBAT", "Nom du champs qui contient la classe Non naturelle", None))
        self.label_sample_path.setText(_translate("PHYMOBAT", "Echantillons RPG (Végétation non naturelle / Semi-naturelle)", None))
        self.lineEdit_select_sample_fieldname_2.setToolTip(_translate("PHYMOBAT", "Nom du champs qui contient la classe Semi-naturelle", None))
        self.lineEdit_sample_path.setToolTip(_translate("PHYMOBAT", "Chemin d\'accès au shapefile RPG", None))
        self.lineEdit_select_sample_class_1.setToolTip(_translate("PHYMOBAT", "Intitulé de la classe dans le shapefile", None))
        self.label_select_sample_class.setText(_translate("PHYMOBAT", "Classes", None))
        self.label_select_sample_class_4.setText(_translate("PHYMOBAT", "Classes", None))
        self.lineEdit_sample_path_2.setToolTip(_translate("PHYMOBAT", "Chemin d\'accès au shapefile des échantillons Herbacés/Ligneux", None))
        self.label_select_sample_fieldname_2.setText(_translate("PHYMOBAT", "Champs", None))
        self.lineEdit_select_sample_class_4.setToolTip(_translate("PHYMOBAT", "Intitulé de la classe dans le shapefile", None))
        self.label_select_sample_nb_poly_2.setText(_translate("PHYMOBAT", "<html><head/><body><p>Nbre de polygones</p></body></html>", None))
        self.label_select_sample_class_3.setText(_translate("PHYMOBAT", "<html><head/><body><p align=\"center\">Herbacés</p></body></html>", None))
        self.lineEdit_select_sample_fieldname_3.setToolTip(_translate("PHYMOBAT", "Nom du champs qui contient la classe Herbacés", None))
        self.pushButton_browser_sample_path_2.setText(_translate("PHYMOBAT", "...", None))
        self.lineEdit_select_sample_fieldname_4.setToolTip(_translate("PHYMOBAT", "Nom du champs qui contient la classe Ligneux", None))
        self.label_sample_path_2.setText(_translate("PHYMOBAT", "Echantillons Herbacés / Ligneux", None))
        self.lineEdit_select_sample_nb_poly_2.setText(_translate("PHYMOBAT", "20", None))
        self.lineEdit_select_sample_class_3.setToolTip(_translate("PHYMOBAT", "Intitulé de la classe dans le shapefile", None))
        self.label_select_sample_class_5.setText(_translate("PHYMOBAT", "<html><head/><body><p align=\"center\">Ligneux</p></body></html>", None))
        self.label_principal_folder.setText(_translate("PHYMOBAT", "Chemin du dossier principal", None))
        self.lineEdit_principal_folder.setToolTip(_translate("PHYMOBAT", "Dossier principal où se trouve tous les fichiers et dossiers des données", None))
        self.pushButton_browser_principal_folder.setToolTip(_translate("PHYMOBAT", "Parcourir", None))
        self.pushButton_browser_principal_folder.setText(_translate("PHYMOBAT", "...", None))
        self.label_year_images.setText(_translate("PHYMOBAT", "Période ou année des images", None))
        self.lineEdit_year_images.setToolTip(_translate("PHYMOBAT", "Période des images à télécharger. Pour 2 périodes : AAAA-MM-DD,AAAA-MM-DD;AAAA-MM-DD,AAAA-MM-DD", None))
        self.label_ex_period.setText(_translate("PHYMOBAT", "Exemple pour 1 periode : AAAA-MM-DD,AAAA-MM-DD", None))
        self.label_area_path.setText(_translate("PHYMOBAT", "Emprise de la zone (shp)", None))
        self.pushButton_browser_area_path.setText(_translate("PHYMOBAT", "...", None))
        self.label_id_theia.setText(_translate("PHYMOBAT", "Identifiant Theia", None))
        self.label_user.setText(_translate("PHYMOBAT", "Utilisateur :", None))
        self.label_password.setText(_translate("PHYMOBAT", "Mot de passe :", None))
        self.lineEdit_password.setToolTip(_translate("PHYMOBAT", "Mot de passe masqué", None))
        self.checkBox_MNT.setText(_translate("PHYMOBAT", "BD Alti (Facutatif)", None))
        self.pushButton_browser_MNT.setText(_translate("PHYMOBAT", "...", None))
        self.checkBox_VHRS.setText(_translate("PHYMOBAT", "Images THRS", None))
        self.pushButton_browser_VHRS.setText(_translate("PHYMOBAT", "...", None))
        self.label_segmentation.setText(_translate("PHYMOBAT", "Segmentation (shp)", None))
        self.pushButton_browser_segmentation.setText(_translate("PHYMOBAT", "...", None))
        self.proxy.setText(_translate("PHYMOBAT", "Proxy", None))
        self.menuMenu.setTitle(_translate("PHYMOBAT", "Menu", None))
        self.menuAide.setTitle(_translate("PHYMOBAT", "Aide", None))
        self.menuMode.setTitle(_translate("PHYMOBAT", "Mode", None))
        self.actionOuvrir.setText(_translate("PHYMOBAT", "Ouvrir", None))
        self.actionSauver.setText(_translate("PHYMOBAT", "Sauver", None))
        self.actionQuiter.setText(_translate("PHYMOBAT", "Quiter", None))
        self.actionAide_de_PHYMOBAT.setText(_translate("PHYMOBAT", "Aide de PHYMOBAT", None))
        self.actionA_propos_de_PHYMOBAT.setText(_translate("PHYMOBAT", "A propos de PHYMOBAT", None))
        self.actionMode_Simplifi.setText(_translate("PHYMOBAT", "Mode Simplifié", None))
        self.actionMode_expert.setText(_translate("PHYMOBAT", "Mode Expert", None))

