#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Form implementation generated from reading ui file 'PHYMOBAT_tab.ui'
#
# Created: Tue Dec 29 18:10:07 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!
#
# This file is part of PHYMOBAT 1.0.
# Copyright 2016 Sylvio Laventure (IRSTEA - UMR TETIS)
# 
# PHYMOBAT 1.0 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# PHYMOBAT 1.0 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with PHYMOBAT 1.0.  If not, see <http://www.gnu.org/licenses/>.

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PHYMOBAT(object):
    """    
    Graphical user interface element to launch Carhab processing.
    
    Form implementation generated from reading ui file ``PHYMOBAT_tab.ui``.
    Created by PyQt4 UI code generator 4.10.4.

    """
    def setupUi(self, PHYMOBAT):
        PHYMOBAT.setObjectName(_fromUtf8("PHYMOBAT"))
        PHYMOBAT.resize(491, 556)
        self.gridLayout = QtGui.QGridLayout(PHYMOBAT)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_multiprocess = QtGui.QCheckBox(PHYMOBAT)
        self.checkBox_multiprocess.setCheckable(True)
        self.checkBox_multiprocess.setChecked(True)
        self.checkBox_multiprocess.setAutoRepeat(False)
        self.checkBox_multiprocess.setObjectName(_fromUtf8("checkBox_multiprocess"))
        self.gridLayout.addWidget(self.checkBox_multiprocess, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(PHYMOBAT)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(PHYMOBAT)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_year_images = QtGui.QLabel(self.tab)
        self.label_year_images.setObjectName(_fromUtf8("label_year_images"))
        self.gridLayout_3.addWidget(self.label_year_images, 3, 0, 1, 2)
        self.pushButton_browser_VHRS = QtGui.QPushButton(self.tab)
        self.pushButton_browser_VHRS.setObjectName(_fromUtf8("pushButton_browser_VHRS"))
        self.gridLayout_3.addWidget(self.pushButton_browser_VHRS, 12, 5, 1, 1)
        self.label_id_theia = QtGui.QLabel(self.tab)
        self.label_id_theia.setObjectName(_fromUtf8("label_id_theia"))
        self.gridLayout_3.addWidget(self.label_id_theia, 8, 0, 1, 2)
        self.label_captor = QtGui.QLabel(self.tab)
        self.label_captor.setObjectName(_fromUtf8("label_captor"))
        self.gridLayout_3.addWidget(self.label_captor, 2, 0, 1, 3)
        self.lineEdit_principal_folder = QtGui.QLineEdit(self.tab)
        self.lineEdit_principal_folder.setObjectName(_fromUtf8("lineEdit_principal_folder"))
        self.gridLayout_3.addWidget(self.lineEdit_principal_folder, 1, 0, 1, 5)
        self.label_password = QtGui.QLabel(self.tab)
        self.label_password.setObjectName(_fromUtf8("label_password"))
        self.gridLayout_3.addWidget(self.label_password, 9, 3, 1, 1)
        self.lineEdit_user = QtGui.QLineEdit(self.tab)
        self.lineEdit_user.setObjectName(_fromUtf8("lineEdit_user"))
        self.gridLayout_3.addWidget(self.lineEdit_user, 9, 1, 1, 1)
        self.label_user = QtGui.QLabel(self.tab)
        self.label_user.setObjectName(_fromUtf8("label_user"))
        self.gridLayout_3.addWidget(self.label_user, 9, 0, 1, 1)
        self.checkBox_VHRS = QtGui.QCheckBox(self.tab)
        self.checkBox_VHRS.setObjectName(_fromUtf8("checkBox_VHRS"))
        self.gridLayout_3.addWidget(self.checkBox_VHRS, 11, 0, 1, 2)
        self.lineEdit_VHRS = QtGui.QLineEdit(self.tab)
        self.lineEdit_VHRS.setObjectName(_fromUtf8("lineEdit_VHRS"))
        self.gridLayout_3.addWidget(self.lineEdit_VHRS, 12, 0, 1, 5)
        self.lineEdit_year_images = QtGui.QLineEdit(self.tab)
        self.lineEdit_year_images.setObjectName(_fromUtf8("lineEdit_year_images"))
        self.gridLayout_3.addWidget(self.lineEdit_year_images, 3, 3, 1, 1)
        self.checkBox_listing = QtGui.QCheckBox(self.tab)
        self.checkBox_listing.setObjectName(_fromUtf8("checkBox_listing"))
        self.gridLayout_3.addWidget(self.checkBox_listing, 6, 0, 1, 2)
        self.comboBox_captor = QtGui.QComboBox(self.tab)
        self.comboBox_captor.setObjectName(_fromUtf8("comboBox_captor"))
        self.gridLayout_3.addWidget(self.comboBox_captor, 2, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 9, 2, 1, 1)
        self.lineEdit_area_path = QtGui.QLineEdit(self.tab)
        self.lineEdit_area_path.setObjectName(_fromUtf8("lineEdit_area_path"))
        self.gridLayout_3.addWidget(self.lineEdit_area_path, 5, 0, 1, 5)
        self.pushButton_browser_area_path = QtGui.QPushButton(self.tab)
        self.pushButton_browser_area_path.setObjectName(_fromUtf8("pushButton_browser_area_path"))
        self.gridLayout_3.addWidget(self.pushButton_browser_area_path, 5, 5, 1, 1)
        self.lineEdit_listing = QtGui.QLineEdit(self.tab)
        self.lineEdit_listing.setObjectName(_fromUtf8("lineEdit_listing"))
        self.gridLayout_3.addWidget(self.lineEdit_listing, 6, 3, 1, 1)
        self.pushButton_browser_principal_folder = QtGui.QPushButton(self.tab)
        self.pushButton_browser_principal_folder.setObjectName(_fromUtf8("pushButton_browser_principal_folder"))
        self.gridLayout_3.addWidget(self.pushButton_browser_principal_folder, 1, 5, 1, 1)
        self.label_principal_folder = QtGui.QLabel(self.tab)
        self.label_principal_folder.setObjectName(_fromUtf8("label_principal_folder"))
        self.gridLayout_3.addWidget(self.label_principal_folder, 0, 0, 1, 2)
        self.label_area_path = QtGui.QLabel(self.tab)
        self.label_area_path.setObjectName(_fromUtf8("label_area_path"))
        self.gridLayout_3.addWidget(self.label_area_path, 4, 0, 1, 2)
        self.checkBox_download = QtGui.QCheckBox(self.tab)
        self.checkBox_download.setObjectName(_fromUtf8("checkBox_download"))
        self.gridLayout_3.addWidget(self.checkBox_download, 7, 0, 1, 2)
        self.lineEdit_password = QtGui.QLineEdit(self.tab)
        self.lineEdit_password.setObjectName(_fromUtf8("lineEdit_password"))
        self.lineEdit_password.setEchoMode(QtGui.QLineEdit.Password)
        self.gridLayout_3.addWidget(self.lineEdit_password, 9, 4, 1, 2)
        self.checkBox_processing = QtGui.QCheckBox(self.tab)
        self.checkBox_processing.setObjectName(_fromUtf8("checkBox_processing"))
        self.gridLayout_3.addWidget(self.checkBox_processing, 10, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 3, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 13, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.checkBox_img_sample = QtGui.QCheckBox(self.tab_2)
        self.checkBox_img_sample.setObjectName(_fromUtf8("checkBox_img_sample"))
        self.gridLayout_4.addWidget(self.checkBox_img_sample, 6, 0, 1, 4)
        self.lineEdit_select_sample_fieldname_2 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_select_sample_fieldname_2.setObjectName(_fromUtf8("lineEdit_select_sample_fieldname_2"))
        self.gridLayout_4.addWidget(self.lineEdit_select_sample_fieldname_2, 3, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(49, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 9, 1, 1, 1)
        self.pushButton_browser_sample_path = QtGui.QPushButton(self.tab_2)
        self.pushButton_browser_sample_path.setObjectName(_fromUtf8("pushButton_browser_sample_path"))
        self.gridLayout_4.addWidget(self.pushButton_browser_sample_path, 1, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(106, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 5, 2, 1, 1)
        self.lineEdit_select_sample_fieldname_1 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_select_sample_fieldname_1.setObjectName(_fromUtf8("lineEdit_select_sample_fieldname_1"))
        self.gridLayout_4.addWidget(self.lineEdit_select_sample_fieldname_1, 3, 2, 1, 1)
        self.pushButton_add_sample = QtGui.QPushButton(self.tab_2)
        self.pushButton_add_sample.setObjectName(_fromUtf8("pushButton_add_sample"))
        self.gridLayout_4.addWidget(self.pushButton_add_sample, 9, 3, 1, 1)
        self.label_select_sample_fieldname = QtGui.QLabel(self.tab_2)
        self.label_select_sample_fieldname.setObjectName(_fromUtf8("label_select_sample_fieldname"))
        self.gridLayout_4.addWidget(self.label_select_sample_fieldname, 3, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(49, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 4, 1, 1, 1)
        self.label_sample_path = QtGui.QLabel(self.tab_2)
        self.label_sample_path.setObjectName(_fromUtf8("label_sample_path"))
        self.gridLayout_4.addWidget(self.label_sample_path, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(49, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 3, 1, 1, 1)
        self.label_select_sample_nb_poly = QtGui.QLabel(self.tab_2)
        self.label_select_sample_nb_poly.setObjectName(_fromUtf8("label_select_sample_nb_poly"))
        self.gridLayout_4.addWidget(self.label_select_sample_nb_poly, 5, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(49, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 5, 1, 1, 1)
        self.pushButton_img_sample = QtGui.QPushButton(self.tab_2)
        self.pushButton_img_sample.setObjectName(_fromUtf8("pushButton_img_sample"))
        self.gridLayout_4.addWidget(self.pushButton_img_sample, 7, 3, 1, 1)
        self.plainTextEdit_sample = QtGui.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_sample.setObjectName(_fromUtf8("plainTextEdit_sample"))
        self.gridLayout_4.addWidget(self.plainTextEdit_sample, 10, 0, 1, 4)
        self.label_select_sample_class = QtGui.QLabel(self.tab_2)
        self.label_select_sample_class.setObjectName(_fromUtf8("label_select_sample_class"))
        self.gridLayout_4.addWidget(self.label_select_sample_class, 4, 0, 1, 1)
        self.lineEdit_select_sample_class_1 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_select_sample_class_1.setObjectName(_fromUtf8("lineEdit_select_sample_class_1"))
        self.gridLayout_4.addWidget(self.lineEdit_select_sample_class_1, 4, 2, 1, 1)
        self.pushButton_clear_sample = QtGui.QPushButton(self.tab_2)
        self.pushButton_clear_sample.setObjectName(_fromUtf8("pushButton_clear_sample"))
        self.gridLayout_4.addWidget(self.pushButton_clear_sample, 9, 2, 1, 1)
        self.checkBox_RPG = QtGui.QCheckBox(self.tab_2)
        self.checkBox_RPG.setObjectName(_fromUtf8("checkBox_RPG"))
        self.gridLayout_4.addWidget(self.checkBox_RPG, 8, 0, 1, 1)
        self.label_select_sample = QtGui.QLabel(self.tab_2)
        self.label_select_sample.setObjectName(_fromUtf8("label_select_sample"))
        self.gridLayout_4.addWidget(self.label_select_sample, 2, 0, 1, 1)
        self.lineEdit_sample_path = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_sample_path.setObjectName(_fromUtf8("lineEdit_sample_path"))
        self.gridLayout_4.addWidget(self.lineEdit_sample_path, 1, 0, 1, 3)
        self.lineEdit_select_sample_nb_poly = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_select_sample_nb_poly.setObjectName(_fromUtf8("lineEdit_select_sample_nb_poly"))
        self.gridLayout_4.addWidget(self.lineEdit_select_sample_nb_poly, 5, 3, 1, 1)
        self.lineEdit_select_sample_class_2 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_select_sample_class_2.setObjectName(_fromUtf8("lineEdit_select_sample_class_2"))
        self.gridLayout_4.addWidget(self.lineEdit_select_sample_class_2, 4, 3, 1, 1)
        self.lineEdit_img_sample = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_img_sample.setObjectName(_fromUtf8("lineEdit_img_sample"))
        self.gridLayout_4.addWidget(self.lineEdit_img_sample, 7, 0, 1, 3)
        self.checkBox_threshold = QtGui.QCheckBox(self.tab_2)
        self.checkBox_threshold.setObjectName(_fromUtf8("checkBox_threshold"))
        self.gridLayout_4.addWidget(self.checkBox_threshold, 13, 0, 1, 3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_browser_output = QtGui.QPushButton(self.tab_3)
        self.pushButton_browser_output.setObjectName(_fromUtf8("pushButton_browser_output"))
        self.gridLayout_2.addWidget(self.pushButton_browser_output, 6, 6, 1, 1)
        self.lineEdit_fieldname_4 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_fieldname_4.setObjectName(_fromUtf8("lineEdit_fieldname_4"))
        self.gridLayout_2.addWidget(self.lineEdit_fieldname_4, 8, 6, 1, 1)
        self.label_area_fieldname = QtGui.QLabel(self.tab_3)
        self.label_area_fieldname.setObjectName(_fromUtf8("label_area_fieldname"))
        self.gridLayout_2.addWidget(self.label_area_fieldname, 8, 1, 1, 1)
        self.label_ouput_fieldname = QtGui.QLabel(self.tab_3)
        self.label_ouput_fieldname.setObjectName(_fromUtf8("label_ouput_fieldname"))
        self.gridLayout_2.addWidget(self.label_ouput_fieldname, 7, 0, 1, 5)
        self.label_id_fieldname = QtGui.QLabel(self.tab_3)
        self.label_id_fieldname.setObjectName(_fromUtf8("label_id_fieldname"))
        self.gridLayout_2.addWidget(self.label_id_fieldname, 8, 0, 1, 1)
        self.lineEdit_fieldname_1 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_fieldname_1.setObjectName(_fromUtf8("lineEdit_fieldname_1"))
        self.gridLayout_2.addWidget(self.lineEdit_fieldname_1, 8, 2, 1, 2)
        self.comboBox_fieldname_3 = QtGui.QComboBox(self.tab_3)
        self.comboBox_fieldname_3.setObjectName(_fromUtf8("comboBox_fieldname_3"))
        self.gridLayout_2.addWidget(self.comboBox_fieldname_3, 9, 5, 1, 1)
        self.label_segmentation = QtGui.QLabel(self.tab_3)
        self.label_segmentation.setObjectName(_fromUtf8("label_segmentation"))
        self.gridLayout_2.addWidget(self.label_segmentation, 3, 0, 1, 4)
        self.pushButton_browser_segmentation = QtGui.QPushButton(self.tab_3)
        self.pushButton_browser_segmentation.setObjectName(_fromUtf8("pushButton_browser_segmentation"))
        self.gridLayout_2.addWidget(self.pushButton_browser_segmentation, 4, 6, 1, 1)
        self.comboBox_fieldname_4 = QtGui.QComboBox(self.tab_3)
        self.comboBox_fieldname_4.setObjectName(_fromUtf8("comboBox_fieldname_4"))
        self.gridLayout_2.addWidget(self.comboBox_fieldname_4, 9, 6, 1, 1)
        self.checkBox_classifier = QtGui.QCheckBox(self.tab_3)
        self.checkBox_classifier.setObjectName(_fromUtf8("checkBox_classifier"))
        self.gridLayout_2.addWidget(self.checkBox_classifier, 10, 0, 1, 3)
        self.comboBox_fieldname_1 = QtGui.QComboBox(self.tab_3)
        self.comboBox_fieldname_1.setObjectName(_fromUtf8("comboBox_fieldname_1"))
        self.gridLayout_2.addWidget(self.comboBox_fieldname_1, 9, 2, 1, 2)
        self.lineEdit_segmentation = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_segmentation.setObjectName(_fromUtf8("lineEdit_segmentation"))
        self.gridLayout_2.addWidget(self.lineEdit_segmentation, 4, 0, 1, 6)
        self.comboBox_fieldname_2 = QtGui.QComboBox(self.tab_3)
        self.comboBox_fieldname_2.setObjectName(_fromUtf8("comboBox_fieldname_2"))
        self.gridLayout_2.addWidget(self.comboBox_fieldname_2, 9, 4, 1, 1)
        self.lineEdit_fieldname_3 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_fieldname_3.setObjectName(_fromUtf8("lineEdit_fieldname_3"))
        self.gridLayout_2.addWidget(self.lineEdit_fieldname_3, 8, 5, 1, 1)
        self.lineEdit_output = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_output.setObjectName(_fromUtf8("lineEdit_output"))
        self.gridLayout_2.addWidget(self.lineEdit_output, 6, 0, 1, 6)
        self.lineEdit_fieldname_2 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_fieldname_2.setObjectName(_fromUtf8("lineEdit_fieldname_2"))
        self.gridLayout_2.addWidget(self.lineEdit_fieldname_2, 8, 4, 1, 1)
        self.label_ouput = QtGui.QLabel(self.tab_3)
        self.label_ouput.setObjectName(_fromUtf8("label_ouput"))
        self.gridLayout_2.addWidget(self.label_ouput, 5, 0, 1, 4)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 11, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)

        self.comboBox_captor.addItem("Landsat")
        self.comboBox_captor.addItem("SpotWorldHeritage")
        self.comboBox_fieldname_1.addItem("ogr.OFTString")
        self.comboBox_fieldname_1.addItem("ogr.OFTReal")
        self.comboBox_fieldname_2.addItem("ogr.OFTString")
        self.comboBox_fieldname_2.addItem("ogr.OFTReal")
        self.comboBox_fieldname_3.addItem("ogr.OFTString")
        self.comboBox_fieldname_3.addItem("ogr.OFTReal")
        self.comboBox_fieldname_4.addItem("ogr.OFTString")
        self.comboBox_fieldname_4.addItem("ogr.OFTReal")

        self.retranslateUi(PHYMOBAT)
        self.tabWidget.setCurrentIndex(0)
#         QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PHYMOBAT.accept)
#         QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PHYMOBAT.reject)
        QtCore.QMetaObject.connectSlotsByName(PHYMOBAT)

    def retranslateUi(self, PHYMOBAT):
        PHYMOBAT.setWindowTitle(_translate("PHYMOBAT", "PHYMOBAT 1.0", None))
        self.checkBox_multiprocess.setText(_translate("PHYMOBAT", "Multi-processing", None))
        self.label_year_images.setText(_translate("PHYMOBAT", "Année des images", None))
        self.pushButton_browser_VHRS.setText(_translate("PHYMOBAT", "...", None))
        self.label_id_theia.setText(_translate("PHYMOBAT", "Identifiant Theia :", None))
        self.label_captor.setText(_translate("PHYMOBAT", "Capteur des images à télécharger", None))
        self.label_password.setText(_translate("PHYMOBAT", "Mot de passe", None))
        self.label_user.setText(_translate("PHYMOBAT", "Utilisateur :", None))
        self.checkBox_VHRS.setText(_translate("PHYMOBAT", "Images THRS", None))
        self.checkBox_listing.setText(_translate("PHYMOBAT", "Images disponibles :", None))
        self.pushButton_browser_area_path.setText(_translate("PHYMOBAT", "...", None))
        self.pushButton_browser_principal_folder.setText(_translate("PHYMOBAT", "...", None))
        self.label_principal_folder.setText(_translate("PHYMOBAT", "Chemin du dossier principal", None))
        self.label_area_path.setText(_translate("PHYMOBAT", "Emprise de la zone (shp)", None))
        self.checkBox_download.setText(_translate("PHYMOBAT", "Télécharger", None))
        self.checkBox_processing.setText(_translate("PHYMOBAT", "Traitement des images", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PHYMOBAT", "Traitement images", None))
        self.checkBox_img_sample.setText(_translate("PHYMOBAT", "Image échantillonnée (Si \"traitement images\" n\'est pas lancé) :", None))
        self.pushButton_browser_sample_path.setText(_translate("PHYMOBAT", "...", None))
        self.pushButton_add_sample.setText(_translate("PHYMOBAT", "Ajouter", None))
        self.label_select_sample_fieldname.setText(_translate("PHYMOBAT", "Champs", None))
        self.label_sample_path.setText(_translate("PHYMOBAT", "Echantillon (shp)", None))
        self.label_select_sample_nb_poly.setText(_translate("PHYMOBAT", "Nombre de polygones", None))
        self.pushButton_img_sample.setText(_translate("PHYMOBAT", "...", None))
        self.plainTextEdit_sample.setPlainText(_translate("PHYMOBAT", "1 - Végétation non naturelle / Semi-naturelle\n"
"2 - Herbacés / Ligneux\n"
"3 - Lingeux denses / mixtes\n"
"\n"
"\n"
"", None))
        self.label_select_sample_class.setText(_translate("PHYMOBAT", "Classes", None))
        self.pushButton_clear_sample.setText(_translate("PHYMOBAT", "Effacer", None))
        self.checkBox_RPG.setText(_translate("PHYMOBAT", "RPG", None))
        self.label_select_sample.setText(_translate("PHYMOBAT", "Sélection par classe de 2", None))
        self.checkBox_threshold.setText(_translate("PHYMOBAT", "Déterminer les seuils optimaux", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PHYMOBAT", "Echantillons", None))
        self.pushButton_browser_output.setText(_translate("PHYMOBAT", "...", None))
        self.label_area_fieldname.setText(_translate("PHYMOBAT", "AREA", None))
        self.label_ouput_fieldname.setText(_translate("PHYMOBAT", "Champs du fichier de sortie", None))
        self.label_id_fieldname.setText(_translate("PHYMOBAT", "ID", None))
        self.label_segmentation.setText(_translate("PHYMOBAT", "Segmentation (shp)", None))
        self.pushButton_browser_segmentation.setText(_translate("PHYMOBAT", "...", None))
        self.checkBox_classifier.setText(_translate("PHYMOBAT", "Classifier", None))
        self.label_ouput.setText(_translate("PHYMOBAT", "Fichier de sortie (shp)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("PHYMOBAT", "Classification", None))

